set -g default-terminal "screen-256color"
setw -g mode-keys vi
set -ga terminal-overrides ",xterm-256color:Tc"
set-option -g status-position bottom
set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"

unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

unbind r
bind r source-file ~/.tmux.conf

set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -r f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send -X copy-selection


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'janoamaral/tokyo-night-tmux'

set -g @tokyo-night-tmux_theme 'night'
set -g @tokyo-night-tmux_transparent 1  # 1 or 0

set -g @resurrect-strategy-nvim 'session'

set -g @tokyo-night-tmux_window_id_style fsquare
set -g @tokyo-night-tmux_pane_id_style hsquare
set -g @tokyo-night-tmux_zoom_id_style dsquare

run '~/.tmux/plugins/tpm/tpm'
