return {
  "xiyaowong/transparent.nvim",
  lazy = false,
  config = function()
    -- Optional, you don't have to run setup.
    require("transparent").setup({
      -- table: default groups
      groups = {
        "Normal",
        "NormalNC",
        "Comment",
        "Constant",
        "Special",
        "Identifier",
        "Statement",
        "PreProc",
        "Type",
        "Underlined",
        "Todo",
        "String",
        "Function",
        "Conditional",
        "Repeat",
        "Operator",
        "Structure",
        "LineNr",
        "NonText",
        "SignColumn",
        "CursorLine",
        "CursorLineNr",
        "StatusLine",
        "StatusLineNC",
        "EndOfBuffer",
        "WhichKeyNormal",
        "TabLine",
        "TabLineFill",
        "NormalFloat",
        "FloatTitle",
        "FloatBorder",
        "FloatFooter",
      },
      -- table: additional groups that should be cleared
      extra_groups = {
        "TelescopePrompt",
        "TelescopeResults",
        "TelescopePreview",
        "TelescopeNormal",
        "TelescopeBorder",
        "TelescopeTitle",
        "TelescopeMatching",
        "TelescopeMultiSelection",
        "TelescopePromptNormal",
        "TelescopePromptBorder",
        "TelescopePromptTitle",
        "HarpoonBorder",
        "HarpoonWindow",
        "DapUIStopNC",
        "DapUIPlayPauseNC",
        "DapUIRestartNC",
        "DapUIUnavailableNC",
        "DapUIStepIntoNC",
        "DapUIStepOverNC",
        "DapUIStepOutNC",
        "DapUIStepBackNC",
        "SnacksNotifierInfo",
        "SnacksNotifierWarn",
        "SnacksNotifierDebug",
        "SnacksNotifierError",
        "SnacksNotifierTrace",
        "SnacksNotifierIconInfo",
        "SnacksNotifierIconWarn",
        "SnacksNotifierIconDebug",
        "SnacksNotifierIconError",
        "SnacksNotifierIconTrace",
        "SnacksNotifierTitleInfo",
        "SnacksNotifierTitleWarn",
        "SnacksNotifierTitleDebug",
        "SnacksNotifierTitleError",
        "SnacksNotifierTitleTrace",
        "SnacksNotifierBorderInfo",
        "SnacksNotifierBorderWarn",
        "SnacksNotifierBorderDebug",
        "SnacksNotifierBorderError",
        "SnacksNotifierBorderTrace",
        "SnacksNotifierFooterInfo",
        "SnacksNotifierFooterWarn",
        "SnacksNotifierFooterDebug",
        "SnacksNotifierFooterError",
        "SnacksNotifierFooterTrace",
        "SnacksScratchTitle",
        "SnacksScratchBorder",
        "SnacksScratchFooter",
        "SnacksBackdrop",
        "SnacksPickerInputBorder",
        "SnacksPickerInputTitle",
        "SnacksPickerBoxTitle",
        "MiniFilesTitleFocused",
        "NeoTreeNormal",
        "NeoTreeNormalNC",
        "FzfLuaNormal",
        "FzfLuaNormalNC",
        "FzfLuaTitle",
        "FzfLuaPreviewTitle",
        "FzfLuaBorder",
        "TroubleNormal",
      },
      -- table: groups you don't want to clear
      exclude_groups = {
        "SnacksNormal",
        "SnacksNormalNC",
      },
      -- function: code to be executed after highlight groups are cleared
      -- Also the user event "TransparentClear" will be triggered
      on_clear = function() end,
    })
  end,
}
